  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Upload files
        uses: appleboy/scp-action@v0.1.7

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          source: "startup.sh,docker-compose.yml"

          target: "/tmp/socks5"



      - name: Deploy VPS

        uses: appleboy/ssh-action@v1

        with:

          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |

            if [ ! -f /opt/socks5/.initialized ]; then

              chmod +x /tmp/socks5/startup.sh

              /tmp/socks5/startup.sh

              touch /opt/socks5/.initialized

            fi


            mkdir -p /opt/socks5


            cp /tmp/socks5/docker-compose.yml /opt/socks5/docker-compose.yml


            echo "Creating environment file"


            printf "SOCKS_USER=%s\nSOCKS_PASSWORD=%s\n" \
              "${{ secrets.SOCKS_USER }}" \
              "${{ secrets.SOCKS_PASSWORD }}" \
              > /opt/socks5/.env


            cd /opt/socks5


            echo "Login GHCR"


            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
              -u "${{ github.actor }}" \
              --password-stdin


            docker compose pull


            docker compose up -d


            docker ps
